# See https://setuptools.readthedocs.io/en/latest/build_meta.html
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "paras"
dynamic = ["version"]
description = "Predictive algorithm for resolving A-domain specificity featurising enzyme and compound in tandem."
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.9"
authors = [
    { name = "Barbara Terlouw", email = "barbara.terlouw@wur.nl" },
]
maintainers = [
    { name = "David Meijer", email = "david.meijer@wur.nl" },
]
keywords = [
    "paras",
    "parasect",
    "non-ribosomal peptide",
    "substrate specificity",
    "prediction",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Framework :: Pytest",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "scipy",
    "biopython",
    "joblib",
    "pikachu-chem",
    "scikit-learn<=1.8.0",
    "ncbi-acc-download>=0.2.5",
    "sqlalchemy",
    "iterative-stratification",
    "imblearn",
    "pandas",
    "seaborn",
]

[project.urls]
Homepage = "https://github.com/BTheDragonMaster/parasect"
Repository = "https://github.com/BTheDragonMaster/parasect"

[project.scripts]
parasect = "parasect.cli_parasect:main"
paras = "parasect.cli_paras:main"

[project.optional-dependencies]
tests = [
    "coverage",
    "pytest",
]
dev = [
    "black[jupyter]",
    "isort",
    "flake8",
    "flake8-black",
    "flake8-bandit",
    "flake8-bugbear",
    "flake8-docstrings",
    "flake8-isort",
    "flake8-print",
    "pep8-naming",
    "darglint",
    "mypy",
    "docstr-coverage",
]

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "parasect.version.VERSION" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"parasect.data" = [
    "*.txt",
    "*.hmm",
    "*.hmm.*",
    "*.tsv",
    "*.fasta",
    "database_files/*.tsv",
    "included_substrates/*.txt",
    "train_domains/*.txt",
    "parasect.db",
]

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
reverse_relative = true

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.doc8]
max-line-length = 120

[tool.coverage.run]
relative_files = true
source = ["parasect"]
omit = [
    "*/tests/*",
    "*/test_*.py",
]

[tool.coverage.report]
show_missing = true
precision = 1
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]
