[pytest]
# Exclude the specific random forest test file relative to this root folder
addopts = --ignore=src/parasect/model_training/rf/test_rf.py
markers =
    integration: Mark a test as an integration test.