version: "3.3"

services:
  paras-server:
    build:
      context: . 
      dockerfile: Dockerfile.server
    image: paras-server
    restart: always
    container_name: paras-server

  paras-client:
    build: 
      context: . 
      dockerfile: Dockerfile.client 
    image: paras-client
    ports:
      - "4010:80"
    restart: always
    container_name: paras-client

networks:
  paras-network:
    driver: bridge