version: "3.3"

services:
  api:
    build:
      context: . 
      dockerfile: Dockerfile.server
    image: paras-server
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
    restart: always

  client:
    build: 
      context: . 
      dockerfile: Dockerfile.client 
      args:
        - SERVER_PORT=${SERVER_PORT}
    image: paras-client
    ports:
      - "${CLIENT_PORT}:80"
    restart: always