# This Dockerfile builds API only
FROM python:3.9 
WORKDIR /app 
COPY ./src/server/ ./
RUN pip install -r ./requirements.txt 
ENV FLASK_ENV production 
EXPOSE $SERVER_PORT 
CMD ["sh", "-c", "gunicorn -b :$SERVER_PORT api:app"]