# This Dockerfile builds API only
FROM python:3.9 
WORKDIR /app 
COPY ./src/server/ ./
RUN pip install -r ./requirements.txt 
ENV FLASK_ENV production 
EXPOSE 4009
RUN apt-get update 
RUN apt-get install -y hmmer2

RUN wget https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.linux_intel64
RUN chmod +x muscle5.1.linux_intel64
RUN mv muscle5.1.linux_intel64 /usr/local/bin/muscle

CMD ["sh", "-c", "gunicorn -b :4009 api:app"]