version: "3.3"

services:
  api:
    build:
      context: . 
      dockerfile: Dockerfile.server
    image: paras-server
    restart: always

  client:
    build: 
      context: . 
      dockerfile: Dockerfile.client 
    image: paras-client
    ports:
      - "4010:80"
    restart: always